name: Build AppImage

on:
  push:
    branches:
      - main  # This triggers the workflow on any push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Necessary to create releases

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Update as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # Install globally

    - name: Create Virtual Environment and Install Package
      run: |
        python make_venv.py

    - name: Build AppImage
      run: |
        mkdir -p dist
        pyinstaller --onefile --name=my_application \
          --add-data "venv/bin:venv/bin" \
          --add-data "venv/lib/python3.8/site-packages:venv/lib/python3.8/site-packages" \
          __main__.py  # Use the correct entry point file

    - name: Rename AppImage
      run: |
        mv dist/my_application dist/my_application.AppImage

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: v${{ github.run_number }}  # Use the run number to generate a version tag
        name: Release v${{ github.run_number }}  # Name of the release
        artifacts: dist/my_application.AppImage

    - name: Upload AppImage
      uses: actions/upload-artifact@v3
      with:
        name: AppImage
        path: dist/my_application.AppImage
